travis:
  secure:
    BINSTAR_TOKEN: Hilvd4oGRyvTvwEJATyuzT1g9geyZ7s6C1x/kLlhT8TAwe/dzCIh4i5kKHloWaQ/r9H3kh1PjmZgY3eAlb4CbNSUTsmO3UuVDq/T3Od/p80zD1H0A53bkDlQZ9z0sole2vwJpCAPlicxyNNOZK/hDMZl1EPYCEBH9jyuf5h1LTwFqzxfDh2Ikc7CPRDZfRNt9QbCEWo9+nglYNHvLVPUtaWplMQck/tSAoCXCEsQEUE2oWmMlcT5PGt2urtbt2cu6CoX4gh1CgzK+CNK54U/je80HkKsRmOkoX/tzhmtUSAmSMIWIMy7Su4iXUdOerZg/rfd+wED8oqFf1RjiOsmFn5RvqbXvIsuRbgMm5auXEDU1qI0vaJ0evC5s3mQ+EUHbaQPJonGKEx0a802bJJzImmSWLkkDecMG4qn8TCEEujhACyYUGz65ArhharR755ra1XZWPyiCsF2IrG89gDz+idjpFlE7Iyq0RMJn3e0eSPlCzaQhLUYZAUFJ2rtVLZIOjuibZ9C/NzK7Gy3GFWwlmTWPzHe2jXxbCxojRLz6YsRBvhY19vewcI6gFVa9SQi5RGhnW/5MFQruwnxnBcGzR17kcx+yeOf7WUCeDzF9ucxQZy2GTdkqUvRPlqXHCC9Ow4wYCSEp8kN0HKsdvXtXdLmPJX3Qv73Lp1915CIj+Q=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
