travis:
  secure:
    BINSTAR_TOKEN: OUwuO5WQWkbcFQYnkxFFnhk1z9CNXJT/2BBQXMNVuOvAYL9Af5Nw0BK4T5RMRpXc/LMZMvlFJbl0u8NTP/HW1ij2l3pq/OsJK9K5ZJYV7b9qniL7+so21ocJzTBE7k5DM4dxMZSP58JeR5wx0zXzPsasbr584nkKEgTwAMh8jAKevQyYjw/wrPTJ2mZuEhZZikxSBiOVdetSOL0vzXBYaEwfqinNRGhVuC7ql2oFrSl1i+vLrwrpLwazSkHJ54K+1W6EyH5cPZAmQmQxLWkGRDvxD1DxWi+UGP2G4XtWA2j5VyDYzdFzepVPzETJ6yAiN//uoaGjiO5Mqp/mYy1EuDuSzgP71u+op28Kh95WwB3vHBhJHCBw1pLx8K+xjlYra+WWleMIDjqplAsAr8GPbEdblC4p98xVjZa32afNLH8Klk4bkdvW++yvPZz68ZUrCJqeEHEiCNRSfBBEqV1tYVPLw1p/ym9jVxVHEHU05v621SsBJ653qgDE2WYTvXK8ay8eRf1FVZn+2V2Dp9U8iqQLPJzkA4hgpaft8/wFvP64YRejbfFqmtN5L5ou6KkX+/feaqYnmKxh5EGZt/tmjzVGYaZjxqPxF2GXOZK3vRNtItC3Q+M3WKHpWwOWUm32Fko9w2WXYtcFqyXQchEFcbINcs8SZK4H5uBw/UBA9sI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
